extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_mill_ci4[];
extern u8 castle_grounds_dl_mill_pal_rgba16[];
extern u8 castle_grounds_dl_water_light_2_rgba16_ci8[];
extern u8 castle_grounds_dl_water_light_2_rgba16_pal_rgba16[];
extern Vtx castle_grounds_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Level_Mesh_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[85];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_002[];
extern Gfx castle_grounds_dl_Level_Mesh_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
