extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern u8 jrb_dl__09002800_ci4[];
extern u8 jrb_dl__09002800_pal_rgba16[];
extern u8 jrb_dl__09003800_ci4[];
extern u8 jrb_dl__09003800_pal_rgba16[];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_0[28];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_1[54];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Gfx mat_jrb_dl_Grass_Example[];
extern Gfx mat_revert_jrb_dl_Grass_Example[];
extern Gfx mat_jrb_dl_f3dlite_material_001[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_001[];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1[];
