extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_Grass_Example[];
extern Gfx mat_revert_jrb_dl_Grass_Example[];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1[];
